### ISSUE TITLE
TypeError URL is not a constructor

### ISSUE THREAD

**Issue by saneq1** [kenigbolo/network-speed#85]
when clicking on the button in "react" it writes "URL is not a constructor"
https://codesandbox.io/s/patient-dust-do1d8?file=/src/App.js

**Comment by kenigbolo** [comment]
Hi, @saneq1 this error is totally understandable, seeing that the description of this package is "Node lightweight module to check network speed (upload/download)". This package works primarily on the server-side since it uses the Node JS `HTTP/https` modules. Do let me know if you have any further questions. Closing this for now

**Comment by sancia15** [comment]
I get the same error pls provide some solution

**Comment by kenigbolo** [comment]
@sancia15 @saneq1 I've updated the package with a patch for this based on @wakingweb suggestion. The caveat however is that when using on clientside, it'll require HTTPS strictly (which IMO is should suffice) however, it'll continue to work on node same way as it previously did.

Updated the code sandbox link here https://codesandbox.io/s/red-rgb-lx1wr to show this in principle. I'll close this issue now, but thanks for letting me know about this, and sorry it took so long - new dad problems :)
